### ISSUE TITLE
Issues running other rake tasks

### ISSUE THREAD

**Issue by framallo** [crismali/fantaskspec#1]
Great gem!

I'm using it to test some rake task. But for some reason it fails to run other rake tasks so this code returns nil

```
Rake::Task['db:populate_uuids'].invoke
```

Both on the spec and the rake context. Any idea what could be the issue?

**Comment by crismali** [comment]
@framallo If you've already used `invoke` on a rake task it and all of the tasks it depend on will be disabled until you call `reenable` on them.

**Comment by crismali** [comment]
@framallo Are you still running into problems with this?
