### ISSUE TITLE
Old dependencies to rake

### ISSUE THREAD

**Issue by andywenk** [crismali/fantaskspec#6]
Hi,

I wanted to give this gem a try but the dependency to rake is super old.

```
fantaskspec was resolved to 0.9.9, which depends on
    rake (~> 10.0)
```

If you have a chance to upgrade it, that would be cool.

Cheers

Andy

**Comment by crismali** [comment]
@andywenk just cut [v1.0](https://github.com/crismali/fantaskspec/releases/tag/v1.0.0). Should take care of this.

**Comment by andywenk** [comment]
+1 thank you ;-)
