### ISSUE TITLE
Option to suppress rake task output 

### ISSUE THREAD

**Issue by petRUShka** [crismali/fantaskspec#8]
Usually it is convenient to have something like this in rake task

``` ruby
task my_task: :environment do
    puts 'Going to update #{count} users'
    ...
    # do some staff
    ...
    puts ' All done now!'
end
```

But I don't want to see 'All done now' and others in my rspec output if it is ok. I think it is good idea to have option to suppress output.

**Comment by crismali** [comment]
I think that's reasonable. In the mean time, [RSpec 3.5 has a matcher](https://www.relishapp.com/rspec/rspec-expectations/v/3-5/docs/built-in-matchers/output-matcher) that could help.

**Comment by crismali** [comment]
Looking back on this it looks like there are many ways to accomplish this in RSpec and that many people may prefer different rules for it. I'm closing this for now but am still open to any future PRs that address this.
