### ISSUE TITLE
unable to infer the name of the task

### ISSUE THREAD

**Issue by dimanyc** [crismali/fantaskspec#9]
running v1.0.0 in rails 4.2.6 with rspec 3.5. `subject.execute` returns the following error:

```
Fantaskspec::AmbiguousNameError:
       unable to infer the name of the task. Please rename your describe/context
       or specify your task name via `let(:task_name) { ... }`
```
I'm requiring `fantaskspec` in `spec_helper` and passing `infer_rake_task_specs_from_file_location!` to `RSpec.config`. 

Here an example of a failing task:

```ruby
namespace :foo do
desc 'does something cool'
  task :hd, [:some_args] => [:environment] do |task, args|
    ...
  end
end
```
and whenever `subject.execute` gets called, I get the error message shown above. 

```ruby
require 'rails_helper'

RSpec.describe "foo:hd", type: :rake do

  it 'should call me maybe'  do
    subject.execute 
  end

end
```

**Comment by crismali** [comment]
`infer_rake_task_specs_from_file_location!` just means that specs in files that are in `spec/lib/tasks` and `spec/tasks` will automatically have the `type: :rake` on them so you can leave it off.

Looks like the tasks aren't loaded in the test environment. [Check this out for how to load them.](https://github.com/crismali/fantaskspec#loading-your-rake-tasks)

**Comment by dimanyc** [comment]
yep! I was missing `Rails.application.load_tasks` in rails_helper. Thanks!
